// Create a shared mock data file to ensure consistency across the application

export const mockProperties = [
  {
    id: "1",
    title: "Moderan stan u centru grada",
    description: "Prostran i svijetao stan u srcu grada, idealan za obitelj ili mlade profesionalce.",
    location: "Zagreb, Donji grad",
    price: 185000,
    bedrooms: 2,
    bathrooms: 1,
    area: 68,
    type: "Stan",
    images: [
      "/placeholder.svg?height=400&width=600&text=Slika+1",
      "/placeholder.svg?height=400&width=600&text=Slika+3",
      "/placeholder.svg?height=400&width=600&text=Slika+2",
      "/placeholder.svg?height=400&width=600&text=Slika+4",
    ],
    features: ["Balkon", "Lift", "Parking", "Klima uređaj", "Blizina javnog prijevoza"],
    dateAdded: new Date().toISOString(),
    featured: true,
    new: true,
    year_built: 2018,
    heating: "Centralno",
    floor: 3,
    total_floors: 5,
    energy_certificate: "B",
  },
  {
    id: "2",
    title: "Luksuzna vila s bazenom",
    description: "Prekrasna vila s pogledom na more, savršena za opuštanje i uživanje.",
    location: "Split, Žnjan",
    price: 750000,
    bedrooms: 4,
    bathrooms: 3,
    area: 220,
    type: "Vila",
    images: [
      "/placeholder.svg?height=400&width=600&text=Slika+1",
      "/placeholder.svg?height=400&width=600&text=Slika+2",
      "/placeholder.svg?height=400&width=600&text=Slika+3",
    ],
    features: ["Bazen", "Vrt", "Terasa", "Garaža", "Pogled na more"],
    dateAdded: new Date().toISOString(),
    featured: true,
    year_built: 2020,
    heating: "Podno grijanje",
    floor: 0,
    total_floors: 2,
    energy_certificate: "A+",
  },
  {
    id: "3",
    title: "Novogradnja - stan s terasom",
    description: "Moderan stan u novogradnji s prostranom terasom i pogledom na grad.",
    location: "Rijeka, Centar",
    price: 210000,
    bedrooms: 3,
    bathrooms: 2,
    area: 85,
    type: "Stan",
    images: [
      "/placeholder.svg?height=400&width=600&text=Slika+1",
      "/placeholder.svg?height=400&width=600&text=Slika+3",
      "/placeholder.svg?height=400&width=600&text=Slika+2",
      "/placeholder.svg?height=400&width=600&text=Slika+4",
    ],
    features: ["Terasa", "Lift", "Parking", "Klima uređaj", "Blizina javnog prijevoza"],
    dateAdded: new Date().toISOString(),
    featured: false,
    new: true,
    year_built: 2023,
    heating: "Centralno",
    floor: 4,
    total_floors: 6,
    energy_certificate: "A",
  },
  {
    id: "4",
    title: "Kuća s vrtom blizu mora",
    description: "Lijepa obiteljska kuća u mirnom dijelu grada, blizu plaže i svih sadržaja.",
    location: "Zadar, Borik",
    price: 320000,
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    type: "Kuća",
    images: [
      "/placeholder.svg?height=400&width=600&text=Slika+1",
      "/placeholder.svg?height=400&width=600&text=Slika+2",
      "/placeholder.svg?height=400&width=600&text=Slika+3",
    ],
    features: ["Vrt", "Terasa", "Parking", "Klima uređaj", "Blizina mora"],
    dateAdded: new Date().toISOString(),
    featured: true,
    new: true,
    year_built: 2010,
    heating: "Centralno plinsko",
    floor: 0,
    total_floors: 2,
    energy_certificate: "C",
  },
  {
    id: "5",
    title: "Penthouse s panoramskim pogledom",
    description: "Luksuzni penthouse s panoramskim pogledom na grad i more.",
    location: "Split, Bačvice",
    price: 450000,
    bedrooms: 3,
    bathrooms: 2,
    area: 110,
    type: "Penthouse",
    images: [
      "/placeholder.svg?height=400&width=600&text=Slika+1",
      "/placeholder.svg?height=400&width=600&text=Slika+2",
    ],
    features: ["Terasa", "Lift", "Parking", "Klima uređaj", "Pogled na more"],
    dateAdded: new Date().toISOString(),
    featured: true,
    year_built: 2015,
    heating: "Centralno",
    floor: 8,
    total_floors: 8,
    energy_certificate: "B",
  },
  {
    id: "6",
    title: "Apartman u turističkom naselju",
    description: "Moderno uređen apartman u popularnom turističkom naselju.",
    location: "Poreč, Centar",
    price: 120000,
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    type: "Apartman",
    images: [
      "/placeholder.svg?height=400&width=600&text=Slika+1",
      "/placeholder.svg?height=400&width=600&text=Slika+2",
    ],
    features: ["Balkon", "Parking", "Klima uređaj", "Blizina plaže", "Bazen"],
    dateAdded: new Date().toISOString(),
    featured: false,
    new: true,
    year_built: 2018,
    heating: "Električno",
    floor: 2,
    total_floors: 3,
    energy_certificate: "B",
  },
  {
    id: "7",
    title: "Obiteljska kuća s garažom",
    description: "Prostrana obiteljska kuća s velikom garažom i uređenim vrtom.",
    location: "Osijek, Retfala",
    price: 280000,
    bedrooms: 4,
    bathrooms: 2,
    area: 150,
    type: "Kuća",
    images: [
      "/placeholder.svg?height=400&width=600&text=Slika+1",
      "/placeholder.svg?height=400&width=600&text=Slika+2",
    ],
    features: ["Vrt", "Garaža", "Terasa", "Klima uređaj", "Blizina škole"],
    dateAdded: new Date().toISOString(),
    featured: true,
    new: true,
    year_built: 2005,
    heating: "Centralno plinsko",
    floor: 0,
    total_floors: 2,
    energy_certificate: "C",
  },
  {
    id: "8",
    title: "Ekskluzivni dupleks u novogradnji",
    description: "Moderan dupleks stan u novogradnji s visokim stropovima i kvalitetnim materijalima.",
    location: "Zagreb, Maksimir",
    price: 320000,
    bedrooms: 3,
    bathrooms: 2,
    area: 95,
    type: "Dupleks",
    images: [
      "/placeholder.svg?height=400&width=600&text=Slika+1",
      "/placeholder.svg?height=400&width=600&text=Slika+2",
    ],
    features: ["Dupleks", "Lift", "Parking", "Klima uređaj", "Novogradnja"],
    dateAdded: new Date().toISOString(),
    featured: false,
    new: true,
    year_built: 2022,
    heating: "Podno grijanje",
    floor: 4,
    total_floors: 5,
    energy_certificate: "A",
  },
]

// Add more properties for IDs 9-50
for (let i = 9; i <= 50; i++) {
  mockProperties.push({
    id: i.toString(),
    title: `Nekretnina ${i}`,
    description: `Opis nekretnine ${i}`,
    location: `Zagreb, Lokacija ${i}`,
    price: 100000 + i * 10000,
    bedrooms: (i % 4) + 1,
    bathrooms: (i % 3) + 1,
    area: 50 + i * 5,
    type: ["Stan", "Kuća", "Vila", "Apartman", "Penthouse"][i % 5],
    images: [
      `/placeholder.svg?height=400&width=600&text=Nekretnina+${i}`,
      `/placeholder.svg?height=400&width=600&text=Nekretnina+${i}+Slika+2`,
    ],
    features: [
      "Parking",
      "Klima uređaj",
      ...(i % 2 === 0 ? ["Balkon"] : []),
      ...(i % 3 === 0 ? ["Lift"] : []),
      ...(i % 4 === 0 ? ["Vrt"] : []),
      ...(i % 5 === 0 ? ["Bazen"] : []),
    ],
    dateAdded: new Date().toISOString(),
    // Add featured and new flags to approximately half of the properties
    featured: i % 4 === 0 || i % 4 === 1,
    new: i % 4 === 0 || i % 4 === 2,
    year_built: 2000 + i,
    heating: ["Centralno", "Podno grijanje", "Električno", "Centralno plinsko"][i % 4],
    floor: i % 8,
    total_floors: 8,
    energy_certificate: ["A+", "A", "B", "C", "D"][i % 5],
  })
}
